#!/bin/bash

data() {
  cat << EOF
apple:banana
orange
Strawberry:lime
EOF
}

declare -a group_a=()
declare -a group_b=()

while read -r line; do
  left="$(echo "$line" | cut -d: -f 1)"
  if [[ -n "$left" ]]; then
    group_a+=("$left")
  fi

  right="$(echo "$line" | cut -s -d: -f 2)"
  if [[ -n "$right" ]]; then
    group_b+=("$right")
  fi
done <<< "$(data)"

echo "group_a: ${group_a[*]}"
echo "group_b: ${group_b[*]}"


