#!/bin/bash

file=$1
numPings=$2
timeout=$3

while read -r line; do
  output=$(ping -c "$numPings" "$line")
  awk 'BEGIN {FS="[=]|[ ]"} NR==3 {print $4,$10,$11}' <<< "$output"
  awk 'BEGIN {mean=0} {mean=mean+$10} END {print mean}' <<< "$output"
done < "$file"
