#!/bin/bash
###############################################################################
usage() {
  cat << EOF
Usage: $(basename "$0") [OPTIONS] <HAYSTACK> <NEEDLE>

Returns true if <NEEDLE> is a subdirectory of <HAYSTACK>.

OPTIONS
  -e          Canonicalize paths. All paths must exist and symlinks are followed.
  -v          Enable verbose output.
  -n  <name>  Name of thing
EOF
}

main() {
  local canon haystack needle verbose name

  # set option defaults
  canon=false
  verbose=false
  name=

  # parse options
  while getopts 'n:ev' flag; do
    case "${flag}" in
      n)
        name="${OPTARG}"
        ;;
      e)
        canon=true
        ;;
      v)
        verbose=true
        ;;
      *) usage ; exit 1 ;; 
    esac
  done

  # check arguments
  shift $((OPTIND-1))
  if (( $# != 2 )); then
    usage
    exit 1
  fi

  # assign arguments
  haystack="${1:-}"
  needle="${2-}"

  printf "canon: %s\n" "$canon"
  printf "verbose: %s\n" "$verbose"
  printf "haystack: %s\n" "$haystack"
  printf "needle: %s\n" "$needle"
  printf "name: %s\n" "$name"
}

main "$@"
