#!/bin/bash

set -ex
sudo apt install build-essential libgtk-3-dev libgnutls28-dev libtiff5-dev libgif-dev libjpeg-dev libpng-dev libxpm-dev libncurses-dev texinfo

cd ~/Code
git clone git://git.sv.gnu.org/emacs.git
cd emacs
./autogen.sh
./configure --with-pgtk
make -j8
#sudo make install
