#!/bin/bash

things=('F+1' 'F+2' 'F+3' 'F-1' 'F-2' 'F-3')
for thing in "${things[@]}"; do
  echo "${thing}stops.txt"
  echo "${thing}final.txt"
done

for thing in 'F+1' 'F+2' 'F+3' 'F-1' 'F-2' 'F-3'; do
  echo "${thing}stops.txt"
  echo "${thing}final.txt"
done
