#!/bin/bash

set -f

case $2 in
  +)
    echo "$1 + $3 = $(($1 + $3))"
    ;;
  -)
    echo "$1 - $3 = $(($1 - $3))"
    ;;
  \*)
    echo "$1 * $3 = $(($1 * $3))"
    ;;
  /)
    echo "$1 / $3 = $(($1 / $3))"
    ;;
  *)
    echo "Invalid operator: $2"
    exit
    ;;
esac
