#!/bin/bash

chkpath() { command -v "$1" &> /dev/null; }

favored_bin() {
  for bin in "$@"; do
    if chkpath "$bin"; then
      printf "%s\n" "$bin"
      break
    fi
  done
}

fetch() {
  local url
  url="$1"

  if [[ -z "$url" ]]; then
    return 1
  fi

  case $(favored_bin "curl" "wget" "busybox") in
    curl)     curl -s -L "$url" ;;
    wget)     wget -q -O - "$url" ;;
    busybox)  busybox wget -q -O - "$url" ;;
  esac
}

fetch "$@"
