#!/bin/bash

for d in ./pictures/*; do
  (
    cd "$d" || exit 1
    for i in *.jpeg; do
      dest="$(echo "$i" | sed "s/jpeg$/jpg/g")"
      #mv "$i" "$(echo "$i" | sed "s/jpeg$/jpg/g")"
      echo "moving $i to $dest"
    done
  )
done


