#!/bin/bash

list_images_in() {
  find "$1" -type f -exec file --mime-type {} \+ | \
    awk -F: '{if ($2 ~/image\//) print $1}'
}

list_images_in "./pictures" | while read -r img; do
  echo "Do something to: $img"
done
