#!/bin/bash

threshold=10
filepath="${1:-}"
if [[ -z "$filepath" ]]; then
  printf "Usage: %s <file>\n\n" "$(basename "$0")"
  printf "Returns 0 if <file> has %s or more comments (#)\n" "$threshold"
  exit 1
fi

if [[ ! -f "$filepath" ]]; then
  printf "No such file: %s\n" "$filepath"
  exit 1
fi

if [[ $(grep -c '^\s*#' "$filepath") -lt "$threshold" ]]; then
  printf "%s: has less then %s comments\n" "$filepath" "$threshold"
  exit 1
fi

printf "%s: has %s or more comments\n" "$filepath" "$threshold"
