#!/bin/bash

echo "Enviar mensaje a todo slos usuarios conectados"
listado=$(who | tr -s " " | cut -d " " -f2 | cut -d':' -f 2)
for i in $listado; do
  echo "Hola muybuenastardes" > "/dev/pts/$i"
done
