#!/bin/bash

#is_uint()  case $1        in '' | *[!0-9]*              ) return 1;; esac ;
#is_int()   case ${1#[-+]} in '' | *[!0-9]*              ) return 1;; esac ;
#is_unum()  case $1        in '' | . | *[!0-9.]* | *.*.* ) return 1;; esac ;
is_num() {  case ${1#[-+]} in '' | . | *[!0-9.]* | *.*.* ) return 1;; esac ; }

if is_num "1.1"; then
  echo "yes, it's a num"
fi
