#!/bin/bash

confirm() {
  local question answer
  question="$1"

  until [[ ${answer} == y ]] || [[ ${answer} == n ]]; do
    read -rp "$question (y/N)? " answer
    answer=${answer:-n}
    answer=${answer,,}
  done

  [[ ${answer} == y ]]
}

if confirm "Continue"; then
  echo "Yes indeed"
else
  echo "No."
fi
