#!/bin/bash

random_range() {
  local range=$((${2:-0} - ${1:-0} + 1))
  printf '%s' "$((${1:-0} + (RANDOM % range)))"
}

random_digits() {
  for (( i = 0; i <= ${1:-0}; i++)); do
    printf '%s' "$((RANDOM % 10))"

    #printf '%s' "$(random_range 0 9)"
  done
  printf '\n'
}

random_digits 5

#random_range 1 10
#random_range 0 10
#random_range 1000 9999
#random_range 0 9

