#!/bin/bash

file="read-newline-missing.txt"
printf "one\ntwo\nthree\nfour" > "$file" 

# misses `four`, which has no newline
while read -r line; do
  echo "bad: $line"
done < "$file"

# catches `four`, despite having no newline
while read -r line || [ -n "$line" ]; do
  echo "good: $line"
done < "$file"
