#!/bin/bash


# $1: path to local file
# $2: url of file containing sha256 hash
sha256_validate_from_url() {
  local filename="$1"
  local hash_url="$2"

  hash_from_url=$(curl -s -L "$hash_url")
  echo "$hash_from_url $filename" | sha256sum -c
}

if sha256_validate_from_url "$1" "$2"; then
  echo "it's a match!"
else
  echo "it's not a match :("
fi
