#!/bin/bash

sha256_validate() { echo "$1  $2" | sha256sum -c; }


# $1: sha256 hash as string
# $2: path to local file
sha256_validate2() {
  local hash_to_compare="$1"
  local filename="$2"

  hash_from_file=$(sha256sum "$filename" | awk '{print $1}')
  [[ "$hash_from_file" == "$hash_to_compare" ]]
}

if sha256_validate "$1" "$2"; then
  echo "it's a match!"
else
  echo "it's not a match :("
fi
