#!/bin/bash

usage() {
  cat << EOF >&2
Usage: $(basename "$0") <FILE> 

Does something with <FILE>
EOF
}

# get arg
file="${1:-}"
if [[ -z "$file" ]]; then
  usage
  exit 1
fi

if [[ ! -f "$file" ]]; then
  printf "No such file: %s\n" "$file"
  exit 1
fi

printf "Cool, the file is: %s\n" "$file"
