#!/bin/bash

set -euo pipefail

username="tf2"
password="C{1toU3kK38uVJk)"
packages=(
  'curl' 'wget' 'file' 'tar' 'bzip2' 'gzip' 'unzip' 'bsdmainutils' 'python3'
  'util-linux' 'ca-certificates' 'binutils' 'bc' 'jq' 'tmux' 'netcat' 'lib32gcc1'
  'lib32stdc++6' 'libsdl2-2.0-0:i386' 'steamcmd' 'libcurl4-gnutls-dev:i386'
)

# require root access
if [[ "$(id -u)" != "0" ]]; then
  printf "This script requires root access. Try \`sudo %s\`.\n" "$0"
  exit 1
fi

# add user if it doesn't exist
if ! id -u "$username" >/dev/null 2>&1; then
  useradd -m -p "$(openssl passwd -1 "$password" "$username")"
  usermod -aG sudo "$username"
fi

# update firewall settings
ufw allow 27015/udp
ufw allow 27015/tcp

# install packages
echo steam steam/license note '' | debconf-set-selections
echo steam steam/question select "I AGREE" | debconf-set-selections
dpkg --add-architecture i386
apt update
apt install "${packages[@]}"

# download and run linuxgm script
wget -O linuxgsm.sh https://linuxgsm.sh
chmod +x linuxgsm.sh
./linuxgsm.sh tf2server

# start tf2server
sudo -u tf2 ./tf2server auto-install
sudo -u tf2 ./tf2server start
