#!/bin/bash

set -euo pipefail
#handle_trap() {
#  local s
#  #s=$?
#  echo "$0: Error on line $LINENO: $BASH_COMMAND"
#  #exit $s
#}

#trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
#IFS=$'\n\t'
#false

handle_term() {
  echo "Ouch, caught SIGTERM!"
}

handle_int() {
  echo "Ouch, caught SIGINT!"
}

trap handle_term TERM
trap handle_int INT

sleep 100
