#!/bin/bash

data() {
  cat << EOF
            "Splatoon"
            "Captain Toad: Treasure Tracker"
            "MARIO KART 8"
            "Mario vs. Donkey Kong - Tipping Stars"
            "Minecraft: Super Mario Edition"
            "PAPER MARIO Color Splash"
            "SUPER MARIO 3D WORLD"
            "The Legend of Zelda - Breath of the Wild"
            "THE LEGEND OF ZELDA - The Wind Waker HD"
            "Yoshi's Woolly World"
EOF
}

data_massaged() {
  while IFS=$'\n' read -r v; do
    printf "%s\n%s\n" "FALSE" "$(echo "$v" | xargs)"
  done <<< "$(data)"
}

mapfile -t < <(data_massaged)
zenity \
  --list \
  --text "Select your game" \
  --radiolist \
  --column "Pick" \
  --column "Game" \
  "${MAPFILE[@]}"
