#!/bin/bash

./bin/testfork &
ppid="$!"
pids=("$ppid")

for child in $(ps --no-headers -o pid --ppid="$ppid"); do
  pids+=("$child")
done

for pid in "${pids[@]}"; do
  while [[ -d "/proc/$pid" ]]; do
    printf "waiting for pid: %s\n" "$child"
    sleep 0.5
  done
done

printf "script exiting\n"
