#!/bin/bash

exec &>> ~/AutoUpdate.log

torrentname="$1"
if [[ -z "$torrentname" ]]; then
  echo "Usage: $0 <torrentname>"
  exit 1
fi

echo "========== Upload Started for $torrentname =========="
if ! gclone copy "$HOME/deluge" "GDrive:{ID}" -P --drive-acknowledge-abuse; then
  echo "========== Upload Failed @ $(date) =========="
else
  echo "========== Upload Completed @ $(date) =========="
fi
