#!/bin/bash

screen_name="AutoUpload"
torrentname="$1"

if screen -list | grep -q "AutoUpload"; then
  echo "screen sesssion $screen_name found"
  screen -S AutoUpload -p 0 -X stuff bash -c "echo '========== Upload Started =========='; gclone copy \"/home/nickname/torrents/deluge\" \"GDrive:{ID}\" -P --drive-acknowledge-abuse; echo '========== Upload Completed @ $(date) =========='; echo 'Upload triggered by $torrentname'; bash ^M"
else
  echo "screen sesssion $screen_name NOT found"
  screen -dRR -S "$screen_name" bash -c "echo '========== Upload Started =========='; gclone copy \"/home/nickname/torrents/deluge\" \"GDrive:{ID}\" -P --drive-acknowledge-abuse; echo '========== Upload Completed @ $(date) =========='; echo 'Upload triggered by $torrentname'; bash"
fi
